name: first workflow

on: workflow_dispatch

jobs:
    say-hello:
        runs-on: ubuntu-latest
        steps:
            - name: Say hello
              run: echo "Hello, world!"
            - name: print googBye
              run: echo "Godbye"
