name: LAB4_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read #to pass Checkov security criteria.
  pull-requests: write #to give the workflow permission to comment on PRs with plan details.

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  TF_VAR_bucket_name: ${{ secrets.TF_BUCKET_NAME }}

jobs:
  build:
    strategy: #to use the same workflow to test in multiple Python versions and the usage of variables.
      fail-fast: false
      matrix:
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest]
        terraform-version: ["1.14.6", "1.13.0", "1.12.0"]
        working-directory: ["./GH_Actions/lab4/terraform"]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: ${{ matrix.terraform-version }}

      - name: Cache Terraform Providers
        id: cache-providers
        uses: actions/cache@v6
        with:
          path: .terraform
          key: terraform-${{ matrix.os }}-${{ hashFiles('**/.terraform.lock.hcl') }}
          restore-keys: |
            terraform-${{ matrix.os }}-

      - name: Terraform Init
        id: init
        run: terraform init -backend-config="bucket=${{ secrets.TF_STATE_BUCKET }}" -backend-config="region=eu-north-1"
        working-directory: ${{ matrix.working-directory }}

      - name: Terraform format check
        id: fmt
        run: terraform fmt -check
        continue-on-error: false
        working-directory: ${{ matrix.working-directory }}

      - name: Terraform Validate
        id: validate
        run: terraform validate
        working-directory: ${{ matrix.working-directory }}

      - name: Checkov GitHub Action
        uses: bridgecrewio/checkov-action@v12

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ${{ matrix.working-directory }}

      - name: Terraform Apply
        id: apply
        if: steps.plan.outcome == 'success' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform apply tfplan
        working-directory: ${{ matrix.working-directory }}

      - name: Terraform output
        id: output
        if: steps.apply.outcome == 'success' && github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: terraform output
        working-directory: ${{ matrix.working-directory }}

      #############################################################
      # Bonus github-script
      #############################################################

      - name: Post Terraform plan details as PR comment
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const fs = require('fs');
            const plan = fs.readFileSync('tfplan', 'utf8');
            const truncated = plan.length > 65000 ? plan.substring(0, 65000) + '\n... (truncated)' : plan;

            const body = `## Terraform Plan
            \`\`\`terraform
            ${truncated}
            \`\`\``;

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: body
            });
