name: LAB1_CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write #to give the workflow permission to commit and push changes back to the repository. not needed right now.

jobs:
  LAB1_Test:
    strategy: #to use the same workflow to test in multiple Python versions and the usage of variables.
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11"]
        working-directory: ["./GH_Actions/lab1"]

    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up python
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        working-directory: ${{ matrix.working-directory }}

      - name: Auto-format with Black
        run: |
          pip install black
          black .
        working-directory: ${{ matrix.working-directory }}

      # - name: Commit and Push formatting fixes #to automatically commit and push any formatting fixes made by Black.
      #   uses: stefanzweifel/git-auto-commit-action@v5
      #   with:
      #     commit_message: "chore: automated format fixes via Black"
      #     branch: main

      - name: lint with flake8
        run: |
          pip install flake8
          flake8 . --format='::warning file=%(path)s,line=%(row)d,col=%(col)d::[Flake8] %(code)s: %(text)s' --exit-zero #force flake 8 to code 0 while still echoing the errors.
        working-directory: ${{ matrix.working-directory }}

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          python -m pytest test_calculator.py --cov=calculator --cov-report=term-missing
        working-directory: ${{ matrix.working-directory }}
